config/routes.rb
Rails.application.routes.draw do

    # Video Tutorials etc
    resources :videos



    # Client's conversations
    resources :conversations do

        member do
          patch :close_conversation
        end

        resources :comments

    end


    get 'data_stores/backup_from_dump'
    get 'data_stores/restore_from_dump'


    # Kekekeke
    get 'data_stores/capture_db'
    get 'data_stores/restore_db'


    get 'data_stores/scheduled_backup'
    get 'data_stores/manual_backup'

    

    # Client Assets
    resources :client_assets




    # Guarantors
    resources :guarantors




    # ActivityLog - Audit Trail
    resources :activity_logs




    # Reports
    resources :reports, only: [:show, :index] do
        collection do
            # loans report
            get :requested_loans
            get :approved_loans
            get :rejected_loans
            get :disbursed_loans
            get :undisbursed_loans


            # Get Members List
            get :loan_types_list


            # Get Loan Policies List
            get :loan_policies_list


            # Accounting, pdf version of accounting_entries#show_income_summary
            get :income_summary


            # Loan Installments Journal for each Loan
            get :loan_journal_entries


            # Get User Logs
            get :activity_logs


            # Get Members List
            get :clients_list
        end
    end





    resources :cr_entries, only: [:edit, :update]




    resources :dr_entries, only: [:edit, :update]




    # AccoutingEntry
    resources :accounting_entries do
        collection do
            get :show_all_loan_entries
            get :show_income_summary
        end
    end




    # ClientDoc
    resources :client_docs




    # LoanSearch, advance search routes
    resources :loan_searches




    # LoanInstallment
    resources :loan_installments do
      member do 
        patch :pay_installment
        patch :unpay_installment
        patch :write_a_note
      end
    end




    # LoanDoc
    resources :loan_docs



    # LoanType
    resources :loan_types




# # compute the installments to be made
#     match 'loans/compute_installments/:id', to: 'loans#compute_installments', via: :post




#     # Check when the Client Submitted a document
#     match 'loans/update_submitted_docs/:id', to: 'loans#update_submitted_docs', via: :patch




#     # Reject or accept a Loan
#     match 'loans/approve_the_loan/:id', to: 'loans#approve_the_loan', via: :patch
#     match 'loans/reject_the_loan/:id', to: 'loans#reject_the_loan', via: :patch




    # Loan Model
    resources :loans do
        collection do
          # return Loans based on status
          get :requested_loans
          get :approved_loans
          get :rejected_loans
          get :disbursed_loans
          get :undisbursed_loans


          # For Loan Disbursion
          get :approved_loans_for_disbursion


          # Red Listed Loans
          get :red_listed_loans
        end



        member do 
          # compute the installments to be made
          post :compute_installments


          # Check when the Client Submitted a document
          patch :update_submitted_docs


          # Reject or accept a Loan
          patch :approve_the_loan
          patch :reject_the_loan


          # Disburse the Loan
          patch :disburse_the_loan


          # loans#show_loan_disbursion
          get :show_loan_disbursion


          # loans#show_accounting_for_loan
          get :show_accounting_for_loan
        end
    end



    # For Activation of Client Accounts
    namespace :clients do
      resources :account_activations, only: [:index, :show, :edit, :update]
    end
    match 'clients/account_activations/:id', to: "clients/account_activations#update", via: :post






    # Profile - Client
    resources :client_profiles do
      member do
        # Shows the Client's Guarantors
        get :show_guarantors

        # Shows the client's Assets
        get :show_assets

        # Shows the client's Loans
        get :show_loan_requests
      end
    end

    
    # Devise Client Account
    devise_for :clients, path: 'clients', controllers:
    {
      registrations:  'clients/registrations',
      sessions:     'clients/sessions',
      confirmations:  'clients/confirmations',
      passwords:    'clients/passwords',
      unlocks:    'clients/unlocks'

      # Not including omniauth because it's not enabled in the clients Model
      # ,omniauth_callbacks: 'clients/omniauth_callbacks'
    }





    # Profile - Accountant
    resources :accountant_profiles

    # Devise Acountant Account
    devise_for :accountants, path: 'accountants', controllers:
    {
      registrations:  'accountants/registrations',
      sessions:     'accountants/sessions',
      confirmations:  'accountants/confirmations',
      passwords:    'accountants/passwords',
      unlocks:    'accountants/unlocks'

      # Not including omniauth because it's not enabled in the accountants Model
      # ,omniauth_callbacks: 'accountants/omniauth_callbacks'
    }




    # Profle - Loan Manager
    resources :loan_manager_profiles

    # Devise LoanManager Account
  	devise_for :loan_managers, path:'loan_managers', controllers:
  	{
  		registrations: 	'loan_managers/registrations',
  		sessions: 		'loan_managers/sessions',
  		confirmations: 	'loan_managers/confirmations',
  		passwords: 		'loan_managers/passwords',
  		unlocks: 		'loan_managers/unlocks'

  		# Not including omniauth because it's not enabled in the LoanManager Model
  		# ,omniauth_callbacks: 'loan_managers/omniauth_callbacks'
  	}




    # Profile - Admin
  	resources :admin_profiles

    # Devise Admin Account
  	devise_for :admins, path: 'admins', controllers: 
  	{
  		registrations: 	'admins/registrations',
  		sessions: 		'admins/sessions',
  		confirmations: 	'admins/confirmations',
  		passwords: 		'admins/passwords',
  		unlocks: 		'admins/unlocks'

  		# Not including omniauth because it's not enabled in the Admin Model
  		# ,omniauth_callbacks: 'admins/omniauth_callbacks'
  	}




    # Article
  	resources :articles do 
        member do
            get :new_article_section
            post :create_article_section
        end
    end



    # Section for Articles
    resources :sections


	


  	# Static Pages
  	# get 'pages/services'
  	# get 'pages/articles'
  	# get 'pages/organization'
  	# get 'pages/about'
  	# get 'pages/contacts'
  	# get 'pages/help'


    resources :pages, only: [:index] do
      collection do
        get :home
        get :articles
        get :services
        get :organization
        get :about
        get :contacts
        get :help
        get :quick_start
      end
    end


    # This is for the Public Pages
    resources :financing, only: [:index] do
      collection do
        get :home
        get :articles
        get :services
        get :organization
        get :about
        get :vision
        get :contacts
        get :help
        get :featured_article
      end

      member do
        get :show_article
      end
    end

    get '/management', to: 'pages#organization'

  	# Root
  	root 'financing#home'
end

app/models/loan.rb
# 2018-04-21

# Title:
# 	Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

# Author: 
# 	Leopoldo Deogenes P. Cuesta II
# 	BS-IT Student
# 	AMA Computer University, College of East Rizal




class Loan < ApplicationRecord
	belongs_to :client
	belongs_to :loan_type


	# This list the Documents that have been submitted thus far
	has_many :submitted_docs, dependent: :destroy	# Join Table
	has_many :loan_docs, through: :submitted_docs


	# In association to LoanInstallmentContainer
	has_one :loan_installment_container, dependent: :destroy



	# AccoutingBook for Loan
	has_one :accounting_book, dependent: :destroy





	# Loan Status Constant
	def self.statuses
		{draft: 'draft', rejected: 'rejected', approved: 'approved', disbursed: 'disbursed'}
	end




	# Scopes
	scope :list_loans, lambda { | status=nil | 
		(where(status: status) unless status.nil?) || all
	}



	# Join Statements
	scope :list_with_loan_type_and_client, lambda { 
		joins(:loan_type, :client)
	}



	# This will return Loans that have unpaid installment numbering more than 3
	scope :red_listed_loans, lambda {
		where id: red_listed_loans_array
	}



	scope :requested_loans, lambda { where status: 'draft' }
	scope :approved_loans, lambda { where status: 'approved' }
	scope :rejected_loans, lambda { where status: 'rejected' }
	scope :disbursed_loans, lambda { where(status: 'disbursed').order("disbursement_date desc") }
	scope :undisbursed_loans, lambda { where ["status='draft' or status='approved' or status='rejected'"] }






	# This is for the Simple Search
	# Search field that queries multiple columns
	def self.simple_search(search_string)

		search_string = search_string.downcase


		the_day = Date.parse(search_string) rescue nil


		if the_day
			start_day = the_day.beginning_of_day
			end_day = the_day.end_of_day
		end


		date_query = ("or application_date between :start and :end" if the_day) || ""
		date_values = {start: start_day, end: end_day} if the_day || {}


		list_with_loan_type_and_client.where("lower(string_id) like :string_id or 
			lower(status) like :loan_status or 
			lower(clients.last_name) like :last_name  or 
			lower(loan_types.name) like :type_name 
			#{date_query}", 
			{
				string_id: "#{search_string}%", 
				loan_status: "#{search_string}%", 
				loan_notes: "#{search_string}%", 
				type_name: "#{search_string}%", 
				last_name: "#{search_string}%"
			}.merge(date_values) )
	end





	 # Generates String ID of a Loan
	def self.identification_string(client)
		"LOAN-#{ '%03d' % [client.id]}#{Time.zone.now.to_i}" if client
	end

	


	# Returns true if the Loan requisites are met
	def evaluate_request
		principal_amt = principal_amount
	    minimum = loan_type.minimum
	    maximum = loan_type.maximum

	    required_documents = loan_type.loan_docs.sort
	    submitted_documents = loan_docs.sort unless loan_docs.nil?

	    errors = []

	    if principal_amt < minimum
	    	errors << "Principal is below minimum"
	    end

	    if principal_amt > maximum
	    	errors << "Principal is greater than maximum"
	    end

	    if required_documents != submitted_documents
	    	errors << "Incomplete submitted documents"
	    end

	    errors
	    
	    #(principal_amt >= minimum && principal_amt <= maximum) && required_documents == submitted_documents
	end





	# Loans where unpaid installments are greater than 3 months
	# Returns the id
	def self.red_listed_loans_array
		 loans = disbursed_loans

		 red_listed_loans = []
		

		 loans.each do |loan|

		 	count = 0
		 	
		 	if loan.loan_installment_container
			 	loan.loan_installment_container.loan_installments.each do |installment|

			 		if installment.state == LoanInstallment.states[:unpaid] && installment.to < Date.current.yesterday
			 			count += 1
			 		end

			 	end

			 	if count >= 3
			 		red_listed_loans << loan.id
			 	end
			 end

		 end

		 red_listed_loans
	end


end

app/controllers/loan_types_controller.rb
# 2018-04-21

# Title:
#   Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

# Author: 
#   Leopoldo Deogenes P. Cuesta II
#   BS-IT Student
#   AMA Computer University, College of East Rizal



class LoanTypesController < ApplicationController
  before_action :set_loan_type, only: [:show, :edit, :update, :destroy]

  # GET /loan_types
  # GET /loan_types.json
  def index
    @loan_types = LoanType.all

    authorize LoanType
  end

  # GET /loan_types/1
  # GET /loan_types/1.json
  def show

    authorize LoanType
  end

  # GET /loan_types/new
  def new
    @loan_type = LoanType.new
    @loan_docs = LoanDoc.all

    authorize LoanType
  end

  # GET /loan_types/1/edit
  def edit
    @loan_docs = LoanDoc.all

    authorize LoanType
  end

  # POST /loan_types
  # POST /loan_types.json
  def create
    @loan_type = LoanType.new(loan_type_params)
    @loan_docs = LoanDoc.all

    authorize LoanType

    respond_to do |format|
      if @loan_type.save
        format.html { redirect_to @loan_type, notice: 'Loan type was successfully created.' }
        format.json { render :show, status: :created, location: @loan_type }
      else
        format.html { render :new }
        format.json { render json: @loan_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loan_types/1
  # PATCH/PUT /loan_types/1.json
  def update
    @loan_docs = LoanDoc.all
    authorize LoanType
    

    respond_to do |format|
      if @loan_type.update(loan_type_params)
        format.html { redirect_to @loan_type, notice: 'Loan type was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan_type }
      else
        format.html { render :edit }
        format.json { render json: @loan_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loan_types/1
  # DELETE /loan_types/1.json
  def destroy
    @loan_type.destroy

    authorize LoanType
    
    respond_to do |format|
      format.html { redirect_to loan_types_url, notice: 'Loan type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan_type
      @loan_type = LoanType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_type_params
      params.require(:loan_type).permit(:name, :code, :interest_mode, :rate, :repayment_method, :duration, :minimum, :maximum, loan_doc_ids: [])
    end
end

app/helpers/loan_types_helper.rb
module LoanTypesHelper
end

app/views/loan_types/_form.html.erb
<!-- 2018-04-21

Title:
  Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
  Leopoldo Deogenes P. Cuesta II
  BS-IT Student
  AMA Computer University, College of East Rizal -->


  

<%= form_with(model: loan_type, local: true) do |form| %>
  <% if loan_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan_type.errors.count, "error") %> prohibited this loan_type from being saved:</h2>

      <ul>
      <% loan_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :loan_type_name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :code %>
    <%= form.text_field :code, id: :loan_type_code, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :interest_mode %>
    <%= form.text_field :interest_mode, id: :loan_type_interest_mode, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :rate, 'Rate (e.g. 0.05)' %>
    <%= form.text_field :rate, id: :loan_type_rate, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :duration, "Duration in months" %>
    <%= form.text_field :duration, id: :loan_type_duration, class: 'form-control' %>

  </div>

  <div class="field form-group">
    <%= form.label :minimum, 'Minimum (Php)' %>
    <%= form.text_field :minimum, id: :loan_type_minimum, class: 'form-control' %>
  </div>


  <div class="field form-group">
    <%= form.label :maximum, 'Maximum (Php)' %>
    <%= form.text_field :maximum, id: :loan_type_maximum, class: 'form-control' %>
  </div>


  <div class="field">
    <%= form.label :repayment_method %>
    <%= form.text_field :repayment_method, id: :loan_type_repayment_method, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :loan_doc_ids , 'Required documents' %>
    <%= form.collection_check_boxes :loan_doc_ids, @loan_docs, :id, :name do | cb | %>
        <% cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "checkbox") + cb.text } %> 
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-lg btn-success" %>
  </div>
<% end %>

app/views/loan_types/edit.html.erb
<div class="row">

	<div class="col-md-6 col-centered">

		<div class="panel panel-default">
			<div class="panel-heading panel-heading-custom">
				<div class="panel-title">
					<span class="h4" >Editing Loan Type</span>

					<div class="pull-right">
						<%= link_to 'Show', @loan_type, class: "btn btn-sm btn-info" %> |
						<%= link_to 'Loan Types', loan_types_path, class: "btn btn-sm btn-info" %>
					</div>
				</div>

				<br/>
				
			</div>

				<div class="row">
					<div class="col-md-10 col-centered">
						<%= render 'form', loan_type: @loan_type %>
					</div>
				</div>
		</div>
		<!-- End Panel Heading -->

	</div>

</div>

app/views/loan_types/index.html.erb
<div class="row">
    <div class="col-md-10 col-centered">   
        <!-- Panel Table -->
        <div class="panel panel-default">

          <div class="panel-heading panel-heading-custom">
            <div class="panel_title_to_the_left">
              Loan Types
            </div>

            <div class="panel_buttons_to_the_right">
                <%= link_to 'New Loan Type', new_loan_type_path, class: 'btn btn-sm btn-success' %>
            </div>
          </div>

          <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Code</th>
                      <th>Interest mode</th>
                      <th>Rate</th>
                      <th>Duration in Months</th>
                      <th>Repayment method</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @loan_types.each do |loan_type| %>
                      <tr>
                        <td><%= loan_type.name %></td>
                        <td><%= loan_type.code %></td>
                        <td><%= loan_type.interest_mode %></td>
                        <td><%= number_to_percentage(loan_type.rate * 100, precision: 0) %></td>
                        <td><%= loan_type.duration %></td>
                        <td><%= loan_type.repayment_method %></td>
                        <td><%= link_to 'Show', loan_type %></td>
                        <td><%= link_to 'Edit', edit_loan_type_path(loan_type) %></td>
                        <td><%= link_to 'Destroy', loan_type, method: :delete, data: { confirm: 'Are you sure?' } if system_user? %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
            </div>
            <!-- End table responsive -->

          </div>
          <!-- End Panel Body -->

        </div>
        <!-- Table Panel End -->

    </div>
    <!-- End of col-md-8 -->
</div>
<!-- Row End -->

app/views/loan_types/new.html.erb
<div class="row">

	<div class="col-md-6 col-centered">

		<div class="panel panel-default">
			<div class="panel-heading panel-heading-custom">
				<div class="panel-title">
					<span class="h4" >New Loan Type</span>

					<div class="pull-right">
						<%= link_to 'Loan Types', loan_types_path, class: "btn btn-sm btn-info" %>
					</div>
				</div>

				<br/>
				
			</div>

				<div class="row">
					<div class="col-md-10 col-centered">

						<%= render 'form', loan_type: @loan_type %>
					</div>
				</div>
		</div>
		<!-- End Panel Heading -->
		

	</div>

</div>

app/views/loan_types/show.html.erb
<div class="row">
    <div class="col-md-6 col-centered">
        <div class="panel panel-default">

            <div class="panel-heading panel-heading-custom">
              <div class="panel-title">
                <td>Name:</td>
                <%= @loan_type.name %>

                <div class="pull-right">
                    <%= link_to 'Edit', edit_loan_type_path(@loan_type), class:"btn btn-sm btn-info" %> |
                    <%= link_to 'Loan Types', loan_types_path, class:"btn btn-sm btn-info" %>
                </div>
              </div>
              <br/>
            </div>

            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-centered">
                      <table class="table">
                              <tr>
                                <td><strong>Code:</strong></td>
                                <td><%= @loan_type.code %></td>
                              </tr>

                              <tr>
                                <td><strong>Interest mode:</strong></td>
                                <td><%= @loan_type.interest_mode %></td>
                              </tr>

                              <tr>
                                <td><strong>Rate:</strong></td>
                                <td><%= number_to_percentage(@loan_type.rate * 100, precision: 0) %></td>
                              </tr>

                              <tr>
                                <td><strong>Duration:</strong></td>
                                <td><%= @loan_type.duration %> months</td>
                              </tr>


                              <tr>
                                <td><strong>Minimum:</strong></td>
                                <td><%= number_to_currency(@loan_type.minimum, unit: "Php ") %></td>
                              </tr>

                              <tr>
                                <td><strong>Maximum:</strong></td>
                                <td><%= number_to_currency(@loan_type.maximum, unit: "Php ") %></td>
                              </tr>



                              <tr>
                                <td><strong>Repayment method:</strong></td>
                                <td><%= @loan_type.repayment_method %></td>
                              </tr>
                              <tr>
                                <td>
                                    <strong>Required documents:</strong>
                                </td>
                                <td>

                                    <ul class="list-unstyled">
                                        <% @loan_type.loan_docs.each do |loan_doc| %>
                                            <li><%= loan_doc.name %></li>
                                        <% end %>
                                    </ul>

                                </td>
                              </tr>


                              
                              
                        </table>
                        <!-- Table End -->


                        

                    </div>
                    <!-- Panel End -->
              </div>
              <!-- Row End -->
          </div>
          <!-- Panel Body End -->
          

        </div>
        <!-- Panel End -->
    </div>
</div>