config/routes.rb
Rails.application.routes.draw do

    # Video Tutorials etc
    resources :videos



    # Client's conversations
    resources :conversations do

        member do
          patch :close_conversation
        end

        resources :comments

    end


    get 'data_stores/backup_from_dump'
    get 'data_stores/restore_from_dump'


    # Kekekeke
    get 'data_stores/capture_db'
    get 'data_stores/restore_db'


    get 'data_stores/scheduled_backup'
    get 'data_stores/manual_backup'

    

    # Client Assets
    resources :client_assets




    # Guarantors
    resources :guarantors




    # ActivityLog - Audit Trail
    resources :activity_logs




    # Reports
    resources :reports, only: [:show, :index] do
        collection do
            # loans report
            get :requested_loans
            get :approved_loans
            get :rejected_loans
            get :disbursed_loans
            get :undisbursed_loans


            # Get Members List
            get :loan_types_list


            # Get Loan Policies List
            get :loan_policies_list


            # Accounting, pdf version of accounting_entries#show_income_summary
            get :income_summary


            # Loan Installments Journal for each Loan
            get :loan_journal_entries


            # Get User Logs
            get :activity_logs


            # Get Members List
            get :clients_list
        end
    end





    resources :cr_entries, only: [:edit, :update]




    resources :dr_entries, only: [:edit, :update]




    # AccoutingEntry
    resources :accounting_entries do
        collection do
            get :show_all_loan_entries
            get :show_income_summary
        end
    end




    # ClientDoc
    resources :client_docs




    # LoanSearch, advance search routes
    resources :loan_searches




    # LoanInstallment
    resources :loan_installments do
      member do 
        patch :pay_installment
        patch :unpay_installment
        patch :write_a_note
      end
    end




    # LoanDoc
    resources :loan_docs



    # LoanType
    resources :loan_types




# # compute the installments to be made
#     match 'loans/compute_installments/:id', to: 'loans#compute_installments', via: :post




#     # Check when the Client Submitted a document
#     match 'loans/update_submitted_docs/:id', to: 'loans#update_submitted_docs', via: :patch




#     # Reject or accept a Loan
#     match 'loans/approve_the_loan/:id', to: 'loans#approve_the_loan', via: :patch
#     match 'loans/reject_the_loan/:id', to: 'loans#reject_the_loan', via: :patch




    # Loan Model
    resources :loans do
        collection do
          # return Loans based on status
          get :requested_loans
          get :approved_loans
          get :rejected_loans
          get :disbursed_loans
          get :undisbursed_loans


          # For Loan Disbursion
          get :approved_loans_for_disbursion


          # Red Listed Loans
          get :red_listed_loans
        end



        member do 
          # compute the installments to be made
          post :compute_installments


          # Check when the Client Submitted a document
          patch :update_submitted_docs


          # Reject or accept a Loan
          patch :approve_the_loan
          patch :reject_the_loan


          # Disburse the Loan
          patch :disburse_the_loan


          # loans#show_loan_disbursion
          get :show_loan_disbursion


          # loans#show_accounting_for_loan
          get :show_accounting_for_loan
        end
    end



    # For Activation of Client Accounts
    namespace :clients do
      resources :account_activations, only: [:index, :show, :edit, :update]
    end
    match 'clients/account_activations/:id', to: "clients/account_activations#update", via: :post






    # Profile - Client
    resources :client_profiles do
      member do
        # Shows the Client's Guarantors
        get :show_guarantors

        # Shows the client's Assets
        get :show_assets

        # Shows the client's Loans
        get :show_loan_requests
      end
    end

    
    # Devise Client Account
    devise_for :clients, path: 'clients', controllers:
    {
      registrations:  'clients/registrations',
      sessions:     'clients/sessions',
      confirmations:  'clients/confirmations',
      passwords:    'clients/passwords',
      unlocks:    'clients/unlocks'

      # Not including omniauth because it's not enabled in the clients Model
      # ,omniauth_callbacks: 'clients/omniauth_callbacks'
    }





    # Profile - Accountant
    resources :accountant_profiles

    # Devise Acountant Account
    devise_for :accountants, path: 'accountants', controllers:
    {
      registrations:  'accountants/registrations',
      sessions:     'accountants/sessions',
      confirmations:  'accountants/confirmations',
      passwords:    'accountants/passwords',
      unlocks:    'accountants/unlocks'

      # Not including omniauth because it's not enabled in the accountants Model
      # ,omniauth_callbacks: 'accountants/omniauth_callbacks'
    }




    # Profle - Loan Manager
    resources :loan_manager_profiles

    # Devise LoanManager Account
  	devise_for :loan_managers, path:'loan_managers', controllers:
  	{
  		registrations: 	'loan_managers/registrations',
  		sessions: 		'loan_managers/sessions',
  		confirmations: 	'loan_managers/confirmations',
  		passwords: 		'loan_managers/passwords',
  		unlocks: 		'loan_managers/unlocks'

  		# Not including omniauth because it's not enabled in the LoanManager Model
  		# ,omniauth_callbacks: 'loan_managers/omniauth_callbacks'
  	}




    # Profile - Admin
  	resources :admin_profiles

    # Devise Admin Account
  	devise_for :admins, path: 'admins', controllers: 
  	{
  		registrations: 	'admins/registrations',
  		sessions: 		'admins/sessions',
  		confirmations: 	'admins/confirmations',
  		passwords: 		'admins/passwords',
  		unlocks: 		'admins/unlocks'

  		# Not including omniauth because it's not enabled in the Admin Model
  		# ,omniauth_callbacks: 'admins/omniauth_callbacks'
  	}




    # Article
  	resources :articles do 
        member do
            get :new_article_section
            post :create_article_section
        end
    end



    # Section for Articles
    resources :sections


	


  	# Static Pages
  	# get 'pages/services'
  	# get 'pages/articles'
  	# get 'pages/organization'
  	# get 'pages/about'
  	# get 'pages/contacts'
  	# get 'pages/help'


    resources :pages, only: [:index] do
      collection do
        get :home
        get :articles
        get :services
        get :organization
        get :about
        get :contacts
        get :help
        get :quick_start
      end
    end


    # This is for the Public Pages
    resources :financing, only: [:index] do
      collection do
        get :home
        get :articles
        get :services
        get :organization
        get :about
        get :vision
        get :contacts
        get :help
        get :featured_article
      end

      member do
        get :show_article
      end
    end

    get '/management', to: 'pages#organization'

  	# Root
  	root 'financing#home'
end

app/models/loan_installment.rb
# 2018-04-21

# Title:
# 	Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

# Author: 
# 	Leopoldo Deogenes P. Cuesta II
# 	BS-IT Student
# 	AMA Computer University, College of East Rizal


class LoanInstallment < ApplicationRecord
	belongs_to :loan_installment_container


	# Loan installment Contant
	def self.states
		{paid: 'paid', unpaid: 'unpaid'}
	end

	def self.overdued_installments
		where("'to' < :now and state = :state", {now: Date.current.yesterday, state: self.states[:unpaid]} )
	end
end

app/controllers/loan_installments_controller.rb
# 2018-04-21

# Title:
#   Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

# Author: 
#   Leopoldo Deogenes P. Cuesta II
#   BS-IT Student
#   AMA Computer University, College of East Rizal



class LoanInstallmentsController < ApplicationController
  before_action :set_loan_installment, only: [:show, :edit, :update, :destroy]

  # GET /loan_installments
  # GET /loan_installments.json
  def index
    @loan_installments = LoanInstallment.all
  end

  # GET /loan_installments/1
  # GET /loan_installments/1.json
  def show

      respond_to do | format |
          format.html

          format.pdf do
              issuer = ("#{current_accountant.last_name} #{current_accountant.first_name}" if current_accountant) || "ACGECCO"

              loan_installment_pdf = LoanInstallmentPdf.new(@loan_installment, view_context, issuer)

              send_data loan_installment_pdf.render, filename: 'loan_installment_receipt.pdf', type: 'application/pdf', disposition: 'inline'
          end
      end
  end





  # GET /loan_installments/new
  def new
    @loan_installment = LoanInstallment.new
  end

  # POST /loan_installments
  # POST /loan_installments.json
  def create
    @loan_installment = LoanInstallment.new(loan_installment_params)

    respond_to do |format|
      if @loan_installment.save
        format.html { redirect_to @loan_installment, notice: 'Loan installment was successfully created.' }
        format.json { render :show, status: :created, location: @loan_installment }
      else
        format.html { render :new }
        format.json { render json: @loan_installment.errors, status: :unprocessable_entity }
      end
    end
  end





  # GET /loan_installments/1/edit
  def edit
  end

  # PATCH/PUT /loan_installments/1
  # PATCH/PUT /loan_installments/1.json
  def update
    respond_to do |format|
      if @loan_installment.update(loan_installment_params)
        format.html { redirect_to @loan_installment, notice: 'Loan installment was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan_installment }
      else
        format.html { render :edit }
        format.json { render json: @loan_installment.errors, status: :unprocessable_entity }
      end
    end
  end





  # DELETE /loan_installments/1
  # DELETE /loan_installments/1.json
  def destroy
    @loan_installment.destroy
    respond_to do |format|
      format.html { redirect_to loan_installments_url, notice: 'Loan installment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  # Set the status to paid
  def pay_installment
    set_loan_installment

    @loan = @loan_installment.loan_installment_container.loan

    

    respond_to do | format |
        
        if @loan.status == Loan.statuses[:disbursed]

            ae_exist = AccountingEntry.where(from_installment: @loan_installment.id).first

            unless ae_exist

                @loan_installment.update(loan_installment_params)

                

                # Record this in the Activity Log
                record(pundit_user, 'Accepted Payment')


                ab = @loan.accounting_book


                remaining_principal = ab.overall_principal_balance - @loan_installment.principal_amount
                remaining_interest = ab.overall_interest_balance - @loan_installment.interest_amount


                ae = ab.create_entry title: "Installment no #{@loan_installment.installment_no}", description: " Payment of #{@loan.client.full_name}", principal_balance: remaining_principal, interest_income_balance: remaining_interest, from_installment: @loan_installment.id
                ae.create_dr_entry description: "Cash", value: @loan_installment.principal_amount + @loan_installment.interest_amount
                ae.create_cr_entry description: "Account receivable", value: @loan_installment.principal_amount
                ae.create_cr_entry description: "Interest income", value: @loan_installment.interest_amount


                amount = (@loan_installment.principal_amount + @loan_installment.interest_amount)
                new_payment_email = LoanMailer.new_payment_notification(@loan, amount)
                new_payment_email.deliver_now
                
          
                ab.overall_principal_balance = remaining_principal
                ab.overall_interest_balance = remaining_interest

                ab.save
            end

            format.js { render 'loan_installments/pay_installment.js.erb' }
        else
            format.js { render 'loan_installments/pay_installment_failed.js.erb' }
        end
    end
  end


  # Set the status to unpaid
  def unpay_installment
    set_loan_installment
    @loan_installment.update(loan_installment_params)

    ae = AccountingEntry.where(from_installment: @loan_installment.id).first


    # note this has a bug wherein if you unpay it will mis-calculate AccountingEntry's principal_balance and interest_income Balance
    unless ae.nil?
        ab = ae.accounting_book
        ab.overall_principal_balance = ab.overall_principal_balance + ae.cr_entries.first.value
        ab.overall_interest_balance = ab.overall_interest_balance + ae.cr_entries.last.value
        ab.save

        ae.destroy
    end

    respond_to do | format |
        format.js { render 'loan_installments/unpay_installment.js.erb' }
    end
  end




  # Set a note
  def write_a_note
    set_loan_installment
    @loan_installment.update loan_installment_params
    
    respond_to do | format |
       format.js { render 'loan_installments/write_a_note.js.erb' }
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan_installment
      @loan_installment = LoanInstallment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_installment_params
      params.require(:loan_installment).permit(:installment_no, :client, :from, :to, :principal_amount, :interest_amount, :decimal, :emi_installment, :state, :notes)
    end
end

app/helpers/loan_installments_helper.rb
module LoanInstallmentsHelper
end

app/views/loan_installments/_btn_pay.html.erb
<!-- 2018-04-21

Title:
	Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
	Leopoldo Deogenes P. Cuesta II
	BS-IT Student
	AMA Computer University, College of East Rizal -->



<%= link_to("Set to paid", {controller: 'loan_installments', action: 'pay_installment', loan_installment:  {state: LoanInstallment.states[:paid]}}, remote: true, method: :patch, id: 'loan_installment_paid_link', class: "btn btn-sm btn-success") %> 

app/views/loan_installments/_btn_unpay.html.erb
<%= link_to("Set to unpaid", {controller: 'loan_installments', action: 'unpay_installment', loan_installment:  {state: LoanInstallment.states[:unpaid]}}, remote: true, method: :patch, id: 'loan_installment_unpaid_link', class: "btn btn-sm btn-success")  %> 

app/views/loan_installments/_form.html.erb
<%= form_with(model: loan_installment, local: true) do |form| %>
  <% if loan_installment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan_installment.errors.count, "error") %> prohibited this loan_installment from being saved:</h2>

      <ul>
      <% loan_installment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :installment_no, 'Installment number' %>
    <%= form.number_field :installment_no, id: :loan_installment_installment_no, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :client %>
    <%= form.text_field :client, id: :loan_installment_client, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :from %>
    <%= form.datetime_select :from, id: :loan_installment_from %>
  </div>

  <div class="field form-group">
    <%= form.label :to %>
    <%= form.datetime_select :to, id: :loan_installment_to %>
  </div>

  <div class="field form-group">
    <%= form.label :principal_amount %>
    <%= form.text_field :principal_amount, id: :loan_installment_principal_amount, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :interest_amount %>
    <%= form.text_field :interest_amount, id: :loan_installment_interest_amount, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :emi_installment, 'EMI installment' %>
    <%= form.text_field :emi_installment, id: :loan_installment_emi_installment, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :state %>
    <%= form.select :state, LoanInstallment.states, {}, id: :loan_installment_state, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :loan_installment_notes, class: 'form-control' %>
  </div>

  <div class="actions form-group">
    <%= form.submit class: 'btn btn-lg btn-success' %>
  </div>
<% end %>

app/views/loan_installments/_installments.html.erb
			<!-- This is a partial listing all LoanInstallments in Loans -->
<div class="row"
		<div class="col-md-12">
				<!-- Panel Table -->
				<div class="panel panel-default">

						  <div class="panel-heading panel-heading-custom">
						      <div class="panel_title_to_the_left">Calculated Installments</div>


						      
						  </div>

						<div class="table-responsive">
							<table class="table table-striped">
							  <thead>
							    <tr>
							      <th>Month number</th>
							      <th>Client</th>
							      <th>From</th>
							      <th>To</th>
							      <th>Principal amount</th>
							      <th>Interest amount</th>
							      <th>Emi installment</th>
							      <th>State</th>
							      <th colspan="3"></th>
							    </tr>
							  </thead>

							  <tbody>
							    <% @loan_installments.order("installment_no ASC").each do |loan_installment| %>
							      <tr>
							        <td><%= loan_installment.installment_no %></td>
							        <td><%= loan_installment.client %></td>
							        <td><%= loan_installment.from.to_date %></td>
							        <td><%= loan_installment.to.to_date %></td>
							        <td><%= number_to_currency(loan_installment.principal_amount, unit: "Php ") %></td>
							        <td><%= number_to_currency(loan_installment.interest_amount, unit: "Php ") %></td>
							        <td><%= number_to_currency(loan_installment.emi_installment, unit: "Php ") %></td>
							        <td><%= loan_installment.state %></td>
							        <td><%= link_to 'Show', loan_installment %></td>
							        <td><%= link_to 'Edit', edit_loan_installment_path(loan_installment) %></td>

							        <% if system_user? %>
							        	<td><%= link_to 'Destroy', loan_installment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
							        <% end %>
							      </tr>
							    <% end %>
							  </tbody>
							</table>
						</div>
						<!-- End Table Responsive -->
				</div>
				<!-- Table Panel End -->

		</div>
		<!-- col md 12 end -->
</div>
<!-- row End -->

app/views/loan_installments/computed_installments.js.erb
$('#loan_installments').replaceWith("<%= j render partial: 'loan_installments/installments.html.erb' %>");

app/views/loan_installments/edit.html.erb
<div class="row">

	<div class="col-md-6 col-centered">

		<div class="panel panel-default">
			<div class="panel-heading panel-heading-custom">
				<div class="panel-title">
					<span class="h4" >Adjust Loan Installment Details</span>

					<div class="pull-right">
						<%= link_to 'Show', @loan_installment, class: "btn btn-sm btn-success" %>
					</div>
				</div>

				<br/>
				
			</div>

				<div class="row">
					<div class="col-md-10 col-centered">
						<%= render 'form', loan_installment: @loan_installment %>
					</div>
				</div>
		</div>
		<!-- End Panel Heading -->

	</div>

</div>

app/views/loan_installments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Loan Installments</h1>

<table>
  <thead>
    <tr>
      <th>Month number</th>
      <th>Client</th>
      <th>From</th>
      <th>To</th>
      <th>Principal amount</th>
      <th>Interest amount</th>
      <th>Emi installment</th>
      <th>State</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loan_installments.order("installment_no ASC").each do |loan_installment| %>
      <tr>
        <td><%= loan_installment.installment_no %></td>
        <td><%= loan_installment.client %></td>
        <td><%= loan_installment.from.to_date %></td>
        <td><%= loan_installment.to.to_date %></td>
        <td><%= number_to_currency(loan_installment.principal_amount, unit: "Php ") %></td>
        <td><%= number_to_currency(loan_installment.interest_amount, unit: "Php ") %></td>
        <td><%= number_to_currency(loan_installment.emi_installment, unit: "Php ") %></td>
        <td><%= loan_installment.state %></td>
        <td><%= loan_installment.notes %></td>
        <td><%= link_to 'Show', loan_installment %></td>
        <td><%= link_to 'Edit', edit_loan_installment_path(loan_installment) %></td>
        <td><%= link_to 'Destroy', loan_installment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Loan Installment', new_loan_installment_path %>

app/views/loan_installments/new.html.erb
<div class="row">

	<div class="col-md-6 col-centered">

		<div class="panel panel-default">
			<div class="panel-heading panel-heading-custom">
				<div class="panel-title">
					<span class="h4" >New Loan Installment</span>

					<div class="pull-right">
						<%= link_to 'Backs', loan_installments_path, class: "btn btn-sm btn-success" %>
					</div>
				</div>

				<br/>
				
			</div>

				<div class="row">
					<div class="col-md-10 col-centered">
						<%= render 'form', loan_installment: @loan_installment %>
					</div>
				</div>
		</div>
		<!-- End Panel Heading -->

	</div>

</div>

app/views/loan_installments/pay_installment.js.erb
$('#the_buttons').children().first().replaceWith("<span class='shiraishi-bold'>Paid</span>");
$('#state').children().first().replaceWith("<span>paid</span>");



$('#state_msg').append("<span class='msg' >updated</span>").hide().fadeIn(500).fadeOut(1000, function() {

	$(".msg").replaceWith('');

});

app/views/loan_installments/pay_installment_failed.js.erb
$('#state_msg').append("<span class='msg-danger' >Loan is not disbursed!</span>").hide().fadeIn(500).fadeOut(5000, function() {

	$(".msg").replaceWith('');

});

app/views/loan_installments/show.html.erb
<div class="row">
    <div class="col-md-6 col-centered">
        <div class="panel panel-default">

            <div class="panel-heading panel-heading-custom">

              <div class="row">
                <div class="col-md-12">
                  <div class="panel_title_to_the_left">
                    Month number:
                    <%= @loan_installment.installment_no %>

                  </div>

                  <div class="panel_buttons_to_the_right" id="the_buttons">


                      <%= content_tag(:span, 'Paid', class: 'shiraishi-bold') if @loan_installment.state == LoanInstallment.states[:paid] %> 

                      

                      <%= link_to("Set to paid", {controller: 'loan_installments', action: 'pay_installment', loan_installment:  {state: LoanInstallment.states[:paid]}}, remote: true, data: {confirm: 'Are you sure?'}, method: :patch, id: 'loan_installment_paid_link', class: "btn btn-sm btn-success") if @loan_installment.state == LoanInstallment.states[:unpaid] %> 

                      |


                      <%= link_to 'Edit', edit_loan_installment_path(@loan_installment), class:"btn btn-sm btn-success" %>
                      <%= " | " if @loan_installment.loan_installment_container.loan.status == "disbursed" %>
                      <%= link_to('Loan details', show_loan_disbursion_loan_path(@loan_installment.loan_installment_container.loan), class:"btn btn-sm btn-success") if @loan_installment.loan_installment_container.loan.status == "disbursed" %>
                  </div>
                </div>
                <!-- col-md-12 End -->
              </div>
              <!-- Row End -->
            </div>

            <div class="panel-body">
                <div class="row">
                    <div class="col-md-10 col-centered">
                      <table class="table">
                              <tr>
                                <td><strong>Client:</strong></td>
                                <td><%= @loan_installment.client %></td>
                              </tr>

                              <tr>
                                <td><strong>From:</strong></td>
                                <td><%= @loan_installment.from %></td>
                              </tr>

                              <tr>
                                <td><strong>To:</strong></td>
                                <td><%= @loan_installment.to %></td>
                              </tr>

                              <tr>
                                <td><strong>Monthly principal:</strong></td>
                                <td><%= number_to_currency @loan_installment.principal_amount, unit: 'Php ' %></td>
                              </tr>


                              <tr>
                                <td><strong>Monthly interest:</strong></td>
                                <td><%= number_to_currency @loan_installment.interest_amount, unit: 'Php ' %></td>
                              </tr>


                              <tr>
                                <td><strong>EMI installment:</strong></td>
                                <td><%= number_to_currency @loan_installment.emi_installment, unit: 'Php ' %></td>
                              </tr>


                              <tr>
                                <td><strong>State:</strong></td>
                                <td id="state"><span><%= @loan_installment.state %></span><span class='pull-right' id="state_msg"></span></td>
                              </tr>


                              <tr>
                                  <td><strong>Notes:</strong></td>
                                  <td>

                                      <!-- Form for Submitting Notes -->
                                      <div class="col-md-12" style="padding:0;">
                                          <%= form_with url: {controller: :loan_installments, action: :write_a_note}, method: :patch, scope: :loan_installment do | form | %>

                                              <div class="field form-group">
                                                <%= form.text_area :notes, id: :loan_installment_notes, class: 'form-control' %>
                                              </div>
                                              <div class="actions">
                                                <%= form.submit 'Save', class: 'btn btn-sm btn-success' %>
                                              </div>
                                          <% end %>


                                          <!-- Where the message is displayed -->
                                          <span id="note_msg">

                                          </span>
                                      </div>

                                      <!-- Notes Submission End -->

                                  </td>
                              </tr>

                              <tr>
                                  <td>

                                  </td>

                                  <td>
                                      <%= link_to "Printable receipt", loan_installment_path(@loan_installment, format: :pdf), class: "link-keyaki" %>
                                  </td>

                              </tr>
                              
                        </table>
                        <!-- Table End -->                       

                    </div>
                    <!-- Panel End -->
              </div>
              <!-- Row End -->
          </div>
          <!-- Panel Body End -->
          

        </div>
        <!-- Panel End -->
    </div>
</div>

app/views/loan_installments/unpay_installment.js.erb
$('#the_buttons').children().first().replaceWith("<%= j render partial: 'btn_pay' %>");
$('#state').children().first().replaceWith("<span>unpaid</span>");



$('#state_msg').append("<span class='msg'>updated</span>").hide().fadeIn(500).fadeOut(1000, function() {

	$(".msg").replaceWith('');

});

app/views/loan_installments/write_a_note.js.erb
$('#note_msg').append('<span class="msg">Notes added</span>').hide().fadeIn(500).fadeOut(1000, function () {

	$('span.msg').replaceWith('');
});