config/routes.rb
Rails.application.routes.draw do

    # Video Tutorials etc
    resources :videos



    # Client's conversations
    resources :conversations do

        member do
          patch :close_conversation
        end

        resources :comments

    end


    get 'data_stores/backup_from_dump'
    get 'data_stores/restore_from_dump'


    # Kekekeke
    get 'data_stores/capture_db'
    get 'data_stores/restore_db'


    get 'data_stores/scheduled_backup'
    get 'data_stores/manual_backup'

    

    # Client Assets
    resources :client_assets




    # Guarantors
    resources :guarantors




    # ActivityLog - Audit Trail
    resources :activity_logs




    # Reports
    resources :reports, only: [:show, :index] do
        collection do
            # loans report
            get :requested_loans
            get :approved_loans
            get :rejected_loans
            get :disbursed_loans
            get :undisbursed_loans


            # Get Members List
            get :loan_types_list


            # Get Loan Policies List
            get :loan_policies_list


            # Accounting, pdf version of accounting_entries#show_income_summary
            get :income_summary


            # Loan Installments Journal for each Loan
            get :loan_journal_entries


            # Get User Logs
            get :activity_logs


            # Get Members List
            get :clients_list
        end
    end





    resources :cr_entries, only: [:edit, :update]




    resources :dr_entries, only: [:edit, :update]




    # AccoutingEntry
    resources :accounting_entries do
        collection do
            get :show_all_loan_entries
            get :show_income_summary
        end
    end




    # ClientDoc
    resources :client_docs




    # LoanSearch, advance search routes
    resources :loan_searches




    # LoanInstallment
    resources :loan_installments do
      member do 
        patch :pay_installment
        patch :unpay_installment
        patch :write_a_note
      end
    end




    # LoanDoc
    resources :loan_docs



    # LoanType
    resources :loan_types




# # compute the installments to be made
#     match 'loans/compute_installments/:id', to: 'loans#compute_installments', via: :post




#     # Check when the Client Submitted a document
#     match 'loans/update_submitted_docs/:id', to: 'loans#update_submitted_docs', via: :patch




#     # Reject or accept a Loan
#     match 'loans/approve_the_loan/:id', to: 'loans#approve_the_loan', via: :patch
#     match 'loans/reject_the_loan/:id', to: 'loans#reject_the_loan', via: :patch




    # Loan Model
    resources :loans do
        collection do
          # return Loans based on status
          get :requested_loans
          get :approved_loans
          get :rejected_loans
          get :disbursed_loans
          get :undisbursed_loans


          # For Loan Disbursion
          get :approved_loans_for_disbursion


          # Red Listed Loans
          get :red_listed_loans
        end



        member do 
          # compute the installments to be made
          post :compute_installments


          # Check when the Client Submitted a document
          patch :update_submitted_docs


          # Reject or accept a Loan
          patch :approve_the_loan
          patch :reject_the_loan


          # Disburse the Loan
          patch :disburse_the_loan


          # loans#show_loan_disbursion
          get :show_loan_disbursion


          # loans#show_accounting_for_loan
          get :show_accounting_for_loan
        end
    end



    # For Activation of Client Accounts
    namespace :clients do
      resources :account_activations, only: [:index, :show, :edit, :update]
    end
    match 'clients/account_activations/:id', to: "clients/account_activations#update", via: :post






    # Profile - Client
    resources :client_profiles do
      member do
        # Shows the Client's Guarantors
        get :show_guarantors

        # Shows the client's Assets
        get :show_assets

        # Shows the client's Loans
        get :show_loan_requests
      end
    end

    
    # Devise Client Account
    devise_for :clients, path: 'clients', controllers:
    {
      registrations:  'clients/registrations',
      sessions:     'clients/sessions',
      confirmations:  'clients/confirmations',
      passwords:    'clients/passwords',
      unlocks:    'clients/unlocks'

      # Not including omniauth because it's not enabled in the clients Model
      # ,omniauth_callbacks: 'clients/omniauth_callbacks'
    }





    # Profile - Accountant
    resources :accountant_profiles

    # Devise Acountant Account
    devise_for :accountants, path: 'accountants', controllers:
    {
      registrations:  'accountants/registrations',
      sessions:     'accountants/sessions',
      confirmations:  'accountants/confirmations',
      passwords:    'accountants/passwords',
      unlocks:    'accountants/unlocks'

      # Not including omniauth because it's not enabled in the accountants Model
      # ,omniauth_callbacks: 'accountants/omniauth_callbacks'
    }




    # Profle - Loan Manager
    resources :loan_manager_profiles

    # Devise LoanManager Account
  	devise_for :loan_managers, path:'loan_managers', controllers:
  	{
  		registrations: 	'loan_managers/registrations',
  		sessions: 		'loan_managers/sessions',
  		confirmations: 	'loan_managers/confirmations',
  		passwords: 		'loan_managers/passwords',
  		unlocks: 		'loan_managers/unlocks'

  		# Not including omniauth because it's not enabled in the LoanManager Model
  		# ,omniauth_callbacks: 'loan_managers/omniauth_callbacks'
  	}




    # Profile - Admin
  	resources :admin_profiles

    # Devise Admin Account
  	devise_for :admins, path: 'admins', controllers: 
  	{
  		registrations: 	'admins/registrations',
  		sessions: 		'admins/sessions',
  		confirmations: 	'admins/confirmations',
  		passwords: 		'admins/passwords',
  		unlocks: 		'admins/unlocks'

  		# Not including omniauth because it's not enabled in the Admin Model
  		# ,omniauth_callbacks: 'admins/omniauth_callbacks'
  	}




    # Article
  	resources :articles do 
        member do
            get :new_article_section
            post :create_article_section
        end
    end



    # Section for Articles
    resources :sections


	


  	# Static Pages
  	# get 'pages/services'
  	# get 'pages/articles'
  	# get 'pages/organization'
  	# get 'pages/about'
  	# get 'pages/contacts'
  	# get 'pages/help'


    resources :pages, only: [:index] do
      collection do
        get :home
        get :articles
        get :services
        get :organization
        get :about
        get :contacts
        get :help
        get :quick_start
      end
    end


    # This is for the Public Pages
    resources :financing, only: [:index] do
      collection do
        get :home
        get :articles
        get :services
        get :organization
        get :about
        get :vision
        get :contacts
        get :help
        get :featured_article
      end

      member do
        get :show_article
      end
    end

    get '/management', to: 'pages#organization'

  	# Root
  	root 'financing#home'
end

app/models/article.rb
# 2018-04-21

# Title:
# 	Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

# Author: 
# 	Leopoldo Deogenes P. Cuesta II
# 	BS-IT Student
# 	AMA Computer University, College of East Rizal


class Article < ApplicationRecord
	has_many :sections, dependent: :destroy


	mount_uploader :image, ImageUploader


	acts_as_list
end

app/controllers/articles_controller.rb
# 2018-04-21

# Title:
#   Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

# Author: 
#   Leopoldo Deogenes P. Cuesta II
#   BS-IT Student
#   AMA Computer University, College of East Rizal


class ArticlesController < ApplicationController
  before_action :set_article, only: [:new_article_section, :create_article_section, :show, :edit, :update, :destroy]





  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order("position asc")

    authorize Article
  end

  # GET /articles/1
  # GET /articles/1.json
  def show

    authorize Article
  end





  # GET /articles/new
  def new
    @article = Article.new
    @article_count = Article.count + 1

    authorize Article
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    authorize Article

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        @article_count = Article.count + 1

        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end





  # GET /articles/1/edit
  def edit
    @article_count = Article.count
    authorize Article
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    authorize Article

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        @article_count = Article.count

        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end





  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    authorize Article

    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end




  # GET /articles/1/new_article_section
  def new_article_section
    authorize Article

    @section = @article.sections.build
    @section_count = @article.sections.count + 1
  end


  # post /articles/create_article_section
  def create_article_section
    authorize Article

    @section = @article.sections.build(section_params)

    respond_to do | format |
      if @section.save
        format.html { redirect_to @article, notice: "Subsection successfully created!" }
      else
        @section_count = @article.sections.count + 1
        format.html { render 'new_article_section', notice: "Failed to create Subsection" }
      end
    end

  end






  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:image, :title, :body, :position)
    end

    def section_params
      params.require(:section).permit(:image, :body, :position)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<!-- 2018-04-21

Title:
  Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
  Leopoldo Deogenes P. Cuesta II
  BS-IT Student
  AMA Computer University, College of East Rizal -->



<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  


  <div class="field form-group">
    <%= form.label :image %>
    <%= form.file_field :image, accept: "image/jpg, image/jpeg, image/png, image/gif", id: :article_image %>
    <span><%= File.basename(article.image.url) if article.image.present? %></span>
  </div>


  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title, class:'form-control' %>
  </div>


  <div class="field form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :article_body, class:'form-control', rows: 10 %>
  </div>


  <div class="field form-group">
    <%= form.label :position %>
    <%= form.select :position, 1..@article_count, {}, id: :article_title, class:'form-control' %>
  </div>



  <div class="actions">
    <%= form.submit class: 'btn btn-lg btn-success' %>
  </div>
<% end %>

app/views/articles/_section_form.html.erb
<!-- 2018-04-21

Title:
  Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
  Leopoldo Deogenes P. Cuesta II
  BS-IT Student
  AMA Computer University, College of East Rizal -->



<%= form_with(url: create_article_section_article_path(params[:id]), scope: :section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :image %>
    <%= form.file_field :image, accept: "image/jpg, image/jpeg, image/png, image/gif", id: :section_image %>
    <span><%= File.basename(section.image.url) if section.image.present? %></span>
  </div>

  <div class="field form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :section_body, class:'form-control', rows: 10 %>
  </div>

  <div class="field form-group">
    <%= form.label :position %>
    <%= form.select :position, 1..@section_count, {}, id: :article_title, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-lg btn-success' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<!-- 2018-04-21

Title:
	Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
	Leopoldo Deogenes P. Cuesta II
	BS-IT Student
	AMA Computer University, College of East Rizal -->


	
<div class="row">

	<div class="col-md-8 col-centered">

		<div class="panel panel-default">
			<div class="panel-heading panel-heading-custom">

				<div class="row">
					<div class="col-md-12">
						<div class="panel_title_to_the_left">
							Edit Article
						</div>

						<div class="panel_buttons_to_the_right">
							<%= link_to 'Show', @article, class: "btn btn-sm btn-success" %>
							<%= link_to 'Articles', articles_path, class: "btn btn-sm btn-success" %>
						</div>
					</div>

				</div>
			

				
			</div>

				<div class="row">
					<div class="col-md-10 col-centered">

						<%= render 'form', article: @article %>					
					</div>
				</div>
		</div>
		<!-- End Panel Heading -->
		

	</div>

</div>

app/views/articles/index.html.erb
<!-- 2018-04-21

Title:
  Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
  Leopoldo Deogenes P. Cuesta II
  BS-IT Student
  AMA Computer University, College of East Rizal -->


  

<div class="row">
    <div class="col-md-10 col-centered">   
        <!-- Panel Table -->
        <div class="panel panel-default">

          <div class="panel-heading panel-heading-custom">
            <div class="panel_title_to_the_left">
              Articles
            </div>

            <div class="panel_buttons_to_the_right">
                <%= link_to 'New Article', new_article_path, class: 'btn btn-sm btn-success' %>
            </div>
          </div>

          <div class="panel-body">
            <div class="table-responsive">

                <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>Title</th>
                        <th>Body</th>
                        <th>Published at</th>
                        <th>Position</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      
                      <% @articles.each do |article| %>
                        <tr>
                          <td><%= article.title %></td>
                          <td><%= truncate(article.body, length: 50) { link_to '(click for more)', article } %></td>
                          <td><%= article.created_at.to_date %></td>
                          <td><%= article.position %></td>
                          <td><%= link_to 'Show', article %></td>

                          <% if loan_officers? %>
                            <td><%= link_to 'Edit', edit_article_path(article) %></td>
                            <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                          <% end %>
                        </tr>
                      <% end %>
                    </tbody>
                </table>


            </div>
            <!-- End table responsive -->

          </div>
          <!-- End Panel Body -->

        </div>
        <!-- Table Panel End -->

    </div>
    <!-- End of col-md-8 -->
</div>
<!-- Row End -->

app/views/articles/new.html.erb
<!-- 2018-04-21

Title:
	Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
	Leopoldo Deogenes P. Cuesta II
	BS-IT Student
	AMA Computer University, College of East Rizal -->


	

<div class="row">

	<div class="col-md-8 col-centered">

		<div class="panel panel-default">
			<div class="panel-heading panel-heading-custom">

				<div class="row">
					<div class="col-md-12">
						<div class="panel_title_to_the_left">
							Write an Article
						</div>

						<div class="panel_buttons_to_the_right">
							<%= link_to 'articles', articles_path, class: "btn btn-sm btn-success" %>
						</div>
					</div>

				</div>
			

				
			</div>

				<div class="row">
					<div class="col-md-10 col-centered">

						<%= render 'form', article: @article %>					
					</div>
				</div>
		</div>
		<!-- End Panel Heading -->
		

	</div>

</div>

app/views/articles/new_article_section.html.erb
<!-- 2018-04-21

Title:
	Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
	Leopoldo Deogenes P. Cuesta II
	BS-IT Student
	AMA Computer University, College of East Rizal -->



	

<div class="row">

	<div class="col-md-8 col-centered">

		<div class="panel panel-default">
			<div class="panel-heading panel-heading-custom">

				<div class="row">
					<div class="col-md-12">
						<div class="panel_title_to_the_left">
							Add an Article Section
						</div>

						<div class="panel_buttons_to_the_right">
							<%= link_to 'Show', @article, class: "btn btn-sm btn-info" %>
						</div>
					</div>

				</div>
			

				
			</div>

				<div class="row">
					<div class="col-md-10 col-centered">

						<%= render 'section_form', section: @section %>					
					</div>
				</div>
		</div>
		<!-- End Panel Heading -->
		

	</div>

</div>

app/views/articles/show.html.erb
<!-- 2018-04-21

Title:
	Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
	Leopoldo Deogenes P. Cuesta II
	BS-IT Student
	AMA Computer University, College of East Rizal -->




<div class="row">

	<div class="col-md-10 col-centered">

		<div class="panel panel-default">
			<div class="panel-heading panel-heading-custom">
				<div class="row">
					<div class="col-md-12">

						<div class="panel_title_to_the_left">
							Title: <%= @article.title %>
						</div>

						<div class="panel_buttons_to_the_right">

							<% if loan_officers? %>
								<%= link_to 'Add Subsections', new_article_section_article_path(@article), class: "btn btn-sm btn-success" %> |
								<%= link_to 'Edit', edit_article_path(@article), class: "btn btn-sm btn-success" %> |
							<% end %>

							<%= link_to 'Articles', articles_path, class: "btn btn-sm btn-success" %>
						</div>

					</div>
					<!-- col-md-12 End -->
				</div>
				<!-- Row End -->
			</div>

			<div class="panel-body">
				<div class="row">

					<div class="col-md-12">

						<%= image_tag(@article.image.img_450.url, alt: @article.title, class:"img-responsive col-centered") if @article.image? %>
							
					</div>


					<div class="col-md-11 col-centered justify_me">
						<%= @article.body %>
					</div>


				</div>



				<% if @article.sections.any? %>
					<div class="row" style="text-align: center;">
						<% @article.sections.order("position asc").each do | section | %>
							<hr>

							<% if loan_officers? %>
								<%= link_to 'Edit section', edit_section_path(section), class: 'btn btn-sm btn-info' %>
								<%= link_to 'Destroy', section, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-info' %>
							<% end %>


							<p class="paruru-grey"><%= "Section Position: #{section.position}" %></p>
							

							<div class="col-md-12">
								<%= image_tag(section.image.img_450.url, alt: @article.title, class:"img-responsive col-centered") if section.image? %>

							</div>


							<div class="col-md-11 col-centered justify_me">
								<%= section.body %>
							</div>

						<% end %>
						<!-- Each End -->
					</div>
					<!-- Row End -->
				<% end %>
				<!-- Sections End -->

				
			</div>
			<!-- Panel Body End -->

			<div class="panel-footer">
				<center class="paruru-grey"><%= "Article Position: #{@article.position}" %></center>
			</div>
		</div>
		<!-- Panel End -->
		

	</div>
	<!-- col-md-10 End -->
</div>
<!-- End of Row -->