config/routes.rb
Rails.application.routes.draw do

    # Video Tutorials etc
    resources :videos



    # Client's conversations
    resources :conversations do

        member do
          patch :close_conversation
        end

        resources :comments

    end


    get 'data_stores/backup_from_dump'
    get 'data_stores/restore_from_dump'


    # Kekekeke
    get 'data_stores/capture_db'
    get 'data_stores/restore_db'


    get 'data_stores/scheduled_backup'
    get 'data_stores/manual_backup'

    

    # Client Assets
    resources :client_assets




    # Guarantors
    resources :guarantors




    # ActivityLog - Audit Trail
    resources :activity_logs




    # Reports
    resources :reports, only: [:show, :index] do
        collection do
            # loans report
            get :requested_loans
            get :approved_loans
            get :rejected_loans
            get :disbursed_loans
            get :undisbursed_loans


            # Get Members List
            get :loan_types_list


            # Get Loan Policies List
            get :loan_policies_list


            # Accounting, pdf version of accounting_entries#show_income_summary
            get :income_summary


            # Loan Installments Journal for each Loan
            get :loan_journal_entries


            # Get User Logs
            get :activity_logs


            # Get Members List
            get :clients_list
        end
    end





    resources :cr_entries, only: [:edit, :update]




    resources :dr_entries, only: [:edit, :update]




    # AccoutingEntry
    resources :accounting_entries do
        collection do
            get :show_all_loan_entries
            get :show_income_summary
        end
    end




    # ClientDoc
    resources :client_docs




    # LoanSearch, advance search routes
    resources :loan_searches




    # LoanInstallment
    resources :loan_installments do
      member do 
        patch :pay_installment
        patch :unpay_installment
        patch :write_a_note
      end
    end




    # LoanDoc
    resources :loan_docs



    # LoanType
    resources :loan_types




# # compute the installments to be made
#     match 'loans/compute_installments/:id', to: 'loans#compute_installments', via: :post




#     # Check when the Client Submitted a document
#     match 'loans/update_submitted_docs/:id', to: 'loans#update_submitted_docs', via: :patch




#     # Reject or accept a Loan
#     match 'loans/approve_the_loan/:id', to: 'loans#approve_the_loan', via: :patch
#     match 'loans/reject_the_loan/:id', to: 'loans#reject_the_loan', via: :patch




    # Loan Model
    resources :loans do
        collection do
          # return Loans based on status
          get :requested_loans
          get :approved_loans
          get :rejected_loans
          get :disbursed_loans
          get :undisbursed_loans


          # For Loan Disbursion
          get :approved_loans_for_disbursion


          # Red Listed Loans
          get :red_listed_loans
        end



        member do 
          # compute the installments to be made
          post :compute_installments


          # Check when the Client Submitted a document
          patch :update_submitted_docs


          # Reject or accept a Loan
          patch :approve_the_loan
          patch :reject_the_loan


          # Disburse the Loan
          patch :disburse_the_loan


          # loans#show_loan_disbursion
          get :show_loan_disbursion


          # loans#show_accounting_for_loan
          get :show_accounting_for_loan
        end
    end



    # For Activation of Client Accounts
    namespace :clients do
      resources :account_activations, only: [:index, :show, :edit, :update]
    end
    match 'clients/account_activations/:id', to: "clients/account_activations#update", via: :post






    # Profile - Client
    resources :client_profiles do
      member do
        # Shows the Client's Guarantors
        get :show_guarantors

        # Shows the client's Assets
        get :show_assets

        # Shows the client's Loans
        get :show_loan_requests
      end
    end

    
    # Devise Client Account
    devise_for :clients, path: 'clients', controllers:
    {
      registrations:  'clients/registrations',
      sessions:     'clients/sessions',
      confirmations:  'clients/confirmations',
      passwords:    'clients/passwords',
      unlocks:    'clients/unlocks'

      # Not including omniauth because it's not enabled in the clients Model
      # ,omniauth_callbacks: 'clients/omniauth_callbacks'
    }





    # Profile - Accountant
    resources :accountant_profiles

    # Devise Acountant Account
    devise_for :accountants, path: 'accountants', controllers:
    {
      registrations:  'accountants/registrations',
      sessions:     'accountants/sessions',
      confirmations:  'accountants/confirmations',
      passwords:    'accountants/passwords',
      unlocks:    'accountants/unlocks'

      # Not including omniauth because it's not enabled in the accountants Model
      # ,omniauth_callbacks: 'accountants/omniauth_callbacks'
    }




    # Profle - Loan Manager
    resources :loan_manager_profiles

    # Devise LoanManager Account
  	devise_for :loan_managers, path:'loan_managers', controllers:
  	{
  		registrations: 	'loan_managers/registrations',
  		sessions: 		'loan_managers/sessions',
  		confirmations: 	'loan_managers/confirmations',
  		passwords: 		'loan_managers/passwords',
  		unlocks: 		'loan_managers/unlocks'

  		# Not including omniauth because it's not enabled in the LoanManager Model
  		# ,omniauth_callbacks: 'loan_managers/omniauth_callbacks'
  	}




    # Profile - Admin
  	resources :admin_profiles

    # Devise Admin Account
  	devise_for :admins, path: 'admins', controllers: 
  	{
  		registrations: 	'admins/registrations',
  		sessions: 		'admins/sessions',
  		confirmations: 	'admins/confirmations',
  		passwords: 		'admins/passwords',
  		unlocks: 		'admins/unlocks'

  		# Not including omniauth because it's not enabled in the Admin Model
  		# ,omniauth_callbacks: 'admins/omniauth_callbacks'
  	}




    # Article
  	resources :articles do 
        member do
            get :new_article_section
            post :create_article_section
        end
    end



    # Section for Articles
    resources :sections


	


  	# Static Pages
  	# get 'pages/services'
  	# get 'pages/articles'
  	# get 'pages/organization'
  	# get 'pages/about'
  	# get 'pages/contacts'
  	# get 'pages/help'


    resources :pages, only: [:index] do
      collection do
        get :home
        get :articles
        get :services
        get :organization
        get :about
        get :contacts
        get :help
        get :quick_start
      end
    end


    # This is for the Public Pages
    resources :financing, only: [:index] do
      collection do
        get :home
        get :articles
        get :services
        get :organization
        get :about
        get :vision
        get :contacts
        get :help
        get :featured_article
      end

      member do
        get :show_article
      end
    end

    get '/management', to: 'pages#organization'

  	# Root
  	root 'financing#home'
end

app/models/accounting_entry.rb
# 2018-04-21

# Title:
#     Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

# Author: 
#     Leopoldo Deogenes P. Cuesta II
#     BS-IT Student
#     AMA Computer University, College of East Rizal



class AccountingEntry < ApplicationRecord
	belongs_to :accounting_book

	has_many :dr_entries, dependent: :destroy
	has_many :cr_entries, dependent: :destroy






    # description (String)
    # value (decimal)
    def create_dr_entry(options = {})
    	dr = dr_entries.build()
    	dr.description = options[:description]
    	dr.value = options[:value]
    	dr.save
    	dr
    end



    # description (String)
    # value (decimal)
    def create_cr_entry(options = {})
    	cr = cr_entries.build()
    	cr.description = options[:description]
    	cr.value = options[:value]
    	cr.save
    	cr
    end
end

app/controllers/accounting_entries_controller.rb
# 2018-04-21

# Title:
#   Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

# Author: 
#   Leopoldo Deogenes P. Cuesta II
#   BS-IT Student
#   AMA Computer University, College of East Rizal


class AccountingEntriesController < ApplicationController
  before_action :set_accounting_entry, only: [:show, :edit, :update, :destroy]


  helper_method :sort_order_param, :sort_column_param, :search_param




  # GET /accounting_entries
  # GET /accounting_entries.json
  def index
    @accounting_entries = AccountingEntry.all

    authorize AccountingEntry
  end

  # GET /accounting_entries/1
  # GET /accounting_entries/1.json
  def show
    authorize AccountingEntry
  end



  # Shows the journal of all loans
  def show_all_loan_entries
    @loans = Loan.disbursed_loans.paginate(page: params[:page], per_page: 2)

    authorize AccountingEntry
  end


  # Shows income summary
  def show_income_summary
    @loans = Loan.disbursed_loans.paginate(page: params[:page], per_page: 5)

    authorize AccountingEntry
  end





  # GET /accounting_entries/new
  def new
    @accounting_entry = AccountingEntry.new

    authorize AccountingEntry
  end


  # POST /accounting_entries
  # POST /accounting_entries.json
  def create
    @accounting_entry = AccountingEntry.new(accounting_entry_params)

    authorize AccountingEntry

    respond_to do |format|
      if @accounting_entry.save
        format.html { redirect_to @accounting_entry, notice: 'Accounting entry was successfully created.' }
        format.json { render :show, status: :created, location: @accounting_entry }
      else
        format.html { render :new }
        format.json { render json: @accounting_entry.errors, status: :unprocessable_entity }
      end
    end
  end





  # GET /accounting_entries/1/edit
  def edit
    authorize AccountingEntry
  end

  # PATCH/PUT /accounting_entries/1
  # PATCH/PUT /accounting_entries/1.json
  def update
    authorize AccountingEntry

    respond_to do |format|
      if @accounting_entry.update(accounting_entry_params)
        format.html { redirect_to show_accounting_for_loan_loan_path(@accounting_entry.accounting_book.loan), notice: 'Accounting entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @accounting_entry }
      else
        format.html { render :edit }
        format.json { render json: @accounting_entry.errors, status: :unprocessable_entity }
      end
    end
  end





  # DELETE /accounting_entries/1
  # DELETE /accounting_entries/1.json
  def destroy
    @accounting_entry.destroy

    authorize AccountingEntry
    
    respond_to do |format|
      format.html { redirect_to accounting_entries_url, notice: 'Accounting entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting_entry
      @accounting_entry = AccountingEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accounting_entry_params
      params.require(:accounting_entry).permit(:title, :entry_date, :principal_balance, :interest_income_balance, :description)
    end





    # Url params for Sorting
    def sort_column_param
      params[:sort_column] || 'entry_date'
    end

    def sort_order_param
      params[:sort_order] || 'desc'
    end




    # Url params for Simple Search
    def search_param
      params[:loans][:search] if params[:accounting_entries] || nil
    end
    
end

app/helpers/accounting_entries_helper.rb
module AccountingEntriesHelper
end

app/views/accounting_entries/_form.html.erb
<!-- 2018-04-21

Title:
  Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
  Leopoldo Deogenes P. Cuesta II
  BS-IT Student
  AMA Computer University, College of East Rizal -->


<%= form_with(model: accounting_entry, local: true) do |form| %>
  <% if accounting_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accounting_entry.errors.count, "error") %> prohibited this accounting_entry from being saved:</h2>

      <ul>
      <% accounting_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :accounting_entry_title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :entry_date %>
    <%= form.datetime_select :entry_date, id: :accounting_entry_entry_date %>
  </div>

  <div class="field form-group">
    <%= form.label :principal_balance %>
    <%= form.text_field :principal_balance, id: :accounting_entry_principal_balance, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :interest_income_balance %>
    <%= form.text_field :interest_income_balance, id: :accounting_entry_interest_income_balance, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_field :description, id: :accounting_entry_description, class: "form-control" %>
  </div>


  <div class="">
    <p><strong>Debits:</strong></p>
    <% accounting_entry.dr_entries.each do | dr | %>
        <p>
            <%= number_to_currency(dr.value, unit: 'Php ') %>
            <%= link_to "(Click to Change)", edit_dr_entry_path(dr) %>
        </p>
    <% end %>

    <p><strong>Credits:</strong></p>
    <% accounting_entry.cr_entries.each do | cr | %>
        <p>
            <%= number_to_currency(cr.value, unit: 'Php ') %>
            <%= link_to "(Click to Change)", edit_cr_entry_path(cr) %>
            
        </p>
    <% end %>

  </div>


  <div class="actions form-group">
    <%= form.submit class: "btn btn-lg btn-success" %>
  </div>
<% end %>

app/views/accounting_entries/edit.html.erb
<!-- 2018-04-21

Title:
	Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
	Leopoldo Deogenes P. Cuesta II
	BS-IT Student
	AMA Computer University, College of East Rizal -->
	

<div class="row">

	<div class="col-md-6 col-centered">

		<div class="panel panel-default">
			<div class="panel-heading panel-heading-custom">
				<div class="panel-title">
					<span class="h4" >Editing Accounting Entry</span>

					<div class="pull-right">
						<%= link_to 'Back', show_accounting_for_loan_loan_path(@accounting_entry.accounting_book.loan), class: "btn btn-sm btn-info" %>
					</div>
				</div>

				<br/>
				
			</div>

				<div class="row">
					<div class="col-md-10 col-centered">
						<%= render 'form', accounting_entry: @accounting_entry  %>
					</div>
				</div>
		</div>
		<!-- End Panel Heading -->

	</div>

</div>

app/views/accounting_entries/index.html.erb
<!-- 2018-04-21

Title:
  Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
  Leopoldo Deogenes P. Cuesta II
  BS-IT Student
  AMA Computer University, College of East Rizal -->


<p id="notice"><%= notice %></p>

<h1>Accounting Entries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Entry date</th>
      <th>Principal balance</th>
      <th>Interest income balance</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounting_entries.each do |accounting_entry| %>
      <tr>
        <td><%= accounting_entry.title %></td>
        <td><%= accounting_entry.entry_date %></td>
        <td><%= accounting_entry.principal_balance %></td>
        <td><%= accounting_entry.interest_income_balance %></td>
        <td><%= accounting_entry.description %></td>
        <td><%= link_to 'Show', accounting_entry %></td>
        <td><%= link_to 'Edit', edit_accounting_entry_path(accounting_entry) %></td>
        <td><%= link_to 'Destroy', accounting_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accounting Entry', new_accounting_entry_path %>

app/views/accounting_entries/new.html.erb
<!-- 2018-04-21

Title:
	Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
	Leopoldo Deogenes P. Cuesta II
	BS-IT Student
	AMA Computer University, College of East Rizal -->


<h1>New Accounting Entry</h1>

<%= render 'form', accounting_entry: @accounting_entry %>

<%= link_to 'Back', accounting_entries_path %>

app/views/accounting_entries/show.html.erb
<!-- 2018-04-21

Title:
  Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
  Leopoldo Deogenes P. Cuesta II
  BS-IT Student
  AMA Computer University, College of East Rizal -->



<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @accounting_entry.title %>
</p>

<p>
  <strong>Entry date:</strong>
  <%= @accounting_entry.entry_date %>
</p>

<p>
  <strong>Principal balance:</strong>
  <%= @accounting_entry.principal_balance %>
</p>

<p>
  <strong>Interest income balance:</strong>
  <%= @accounting_entry.interest_income_balance %>
</p>

<p>
  <strong>Description:</strong>
  <%= @accounting_entry.description %>
</p>

<%= link_to 'Edit', edit_accounting_entry_path(@accounting_entry) %> |
<%= link_to 'Back', accounting_entries_path %>

app/views/accounting_entries/show_all_loan_entries.html.erb
<!-- 2018-04-21

Title:
	Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
	Leopoldo Deogenes P. Cuesta II
	BS-IT Student
	AMA Computer University, College of East Rizal -->



<div class="col-md-10 col-centered">

		<!-- Panel Table  -->
		<div class="panel panel-default">

			<div class="panel-heading panel-heading-custom">
			      <div class="panel_title_to_the_left" style="font-size: 2em;">Accounting Entries</div>

			</div>


			<!-- Pagination -->
			<div class="center_pagination">
				<%= will_paginate @loans %>
			</div>


		  <% @loans.each do | loan |%>

		  		<% accounting_book = loan.accounting_book %>
		  		<div class="well well-custom">
		  			<div class="well-header">
			  			<div class="well-title"><%= link_to loan.string_id, show_loan_disbursion_loan_path(loan), class: "link-shiraishi" %></div>

			  			<div class="well-right">
				  			<p><strong>Principal balance </strong> <%= number_to_currency accounting_book.overall_principal_balance, unit: "Php " %></p>
				  			<p><strong>Interest balance </strong><%= number_to_currency accounting_book.overall_interest_balance, unit: "Php " %></p>
				  		</div>
			  		</div>

		  			<table class="table">

		  				<thead>
					        <tr>
					            <th class="separate_next_row"></th>
					            <th>Date</th>
					            <th colspan="3">Description</th>
					            <th>Debit</th>
					            <th>Credit</th>
					        </tr>
				        </thead>

				        <tbody>
			        		

					        <% accounting_book.accounting_entries.each_with_index do | acc_entry | %>
					        	<!-- Debit -->
					        	<% acc_entry.dr_entries.each_with_index do | dr_entry, i |%>

					        		<tr>
					        			<td></td>
					        			<td><%= acc_entry.entry_date.to_date if i == 0 %></td>
					        			<td colspan="3"><%= dr_entry.description %></td>
					        			<td><%= number_to_currency(dr_entry.value, unit: "Php ") %></td>
					        			<td></td>
					        		</tr>

					        	<% end %>

					        	<!-- Credit -->
					        	<% acc_entry.cr_entries.each do | cr_entry |%>

					        		<tr>
					        			<td></td>
					        			<td></td>
					        			<td colspan="3"><%= cr_entry.description %></td>
					        			<td></td>
					        			<td><%= number_to_currency(cr_entry.value, unit: "Php ") %></td>
					        		</tr>

					        	<% end %>


					        	<!-- Accounting entry Description -->
					        	<tr>
				        			<td class="separate_next_row"></td>
				        			<td></td>
				        			<td colspan="3"><em><%= acc_entry.description %></em></td>
				        			<td></td>
				        			<td></td>
					        	</tr>


					        	<!-- Empty rows -->
					        	
					        <% end %>
					        <!-- Accounting entries end -->

				    	</tbody>

		  			</table>

		  		</div>

		  	<% end %>
		  	<!-- Loans end -->


		  	<!-- Pagination -->
		  	<div class="center_pagination">
				<%= will_paginate @loans %>
		  	</div>


		</div>
		<!-- Table Panel End-->

</div>
<!-- End col-md-10 -->

app/views/accounting_entries/show_income_summary.html.erb
<!-- 2018-04-21

Title:
	Online Lending and Loan Management with Accounting and Decision Support System for Antipolo City Government Employees Credit Cooperative

Author: 
	Leopoldo Deogenes P. Cuesta II
	BS-IT Student
	AMA Computer University, College of East Rizal -->


	
<div class="col-md-10 col-centered">

		<!-- Panel Table  -->
		<div class="panel panel-default">

			<div class="panel-heading panel-heading-custom">
			      <div class="panel_title_to_the_left" style="font-size: 2em;">Income Summary</div>

			</div>


			<!-- Pagination -->
			<div class="center_pagination">
				<%= will_paginate @loans %>
			</div>



		  <% @loans.each do | loan |%>

		  		<% accounting_book = loan.accounting_book %>
		  		<div class="well well-custom">
		  			<div class="well-header">
			  			<div class="well-title"><%= link_to loan.string_id, show_loan_disbursion_loan_path(loan), class: "link-shiraishi" %></div>

			  			<div class="well-right">
				  			<p>Principal balance <%= number_to_currency accounting_book.overall_principal_balance, unit: "Php " %></p>
				  			<p>Interest balance <%= number_to_currency accounting_book.overall_interest_balance, unit: "Php " %></p>
				  		</div>
			  		</div>

		  			<table class="table">

		  				<% principal_paid = loan.principal_amount - accounting_book.overall_principal_balance %>

		  				<% interest_paid = loan.net_interest - accounting_book.overall_interest_balance %>


				        <tbody>

				        	<tr>
					            <td>Principal</td>
					            <td>Rate</td>
					            <td>Net Loan</td>
					            <td>Net Interest</td>
					            <td>Principal paid</td>
					            <td>Interest paid</td> 
					        </tr>
			        		
			        		<tr>
					            <td class="separate_next_row"><%= number_to_currency(loan.principal_amount, unit: "Php ") %></td>
					            <td><%= number_to_percentage(loan.loan_type.rate * 100, precision: 0) %></td>
					            <td><%= number_to_currency(loan.net_loan, unit: "Php ") %></td>
					            <td><%= number_to_currency(loan.net_interest, unit: "Php ") %></td>
					            <td><%= number_to_currency(principal_paid, unit: "Php ") %></td>
					            <td><%= number_to_currency(interest_paid, unit: "Php ") %></td> 
					        </tr>

					        <tr>
					            <td></td>
					            <td></td>
					            <td></td>
					            <td></td>
					            <td>Principal balance</td>
					            <td>Interest balance</td> 
					        </tr>

					        <tr>
					        	<td class="separate_next_row"></td>
					            <td></td>
					            <td></td>
					            <td></td>

					        	<td><%= number_to_currency(accounting_book.overall_principal_balance, unit: "Php ") %></td>
					            <td><%= number_to_currency(accounting_book.overall_interest_balance, unit: "Php ") %></td> 
					        </tr>


					        <tr>
					        	<td class="separate_next_row"></td>
					            <td></td>
					            <td></td>
					            <td></td>

					        	<td><strong><%= number_to_currency(principal_paid, unit: "Php ") + "/#{number_to_currency loan.principal_amount, unit: 'Php '}" %></strong></td>
					            <td><strong><%= number_to_currency(interest_paid, unit: "Php ") + "/#{number_to_currency loan.net_interest, unit: 'Php '}" %></strong></td> 
					        </tr>


				    	</tbody>

		  			</table>

		  			<div>
		  				<p>Disbursed Fund Expenditure: <%= number_to_currency loan.net_loan, unit: "Php " %></p>
				  		<p>Payback + Interest Income: <%= number_to_currency(principal_paid + interest_paid, unit: "Php ") %></p>
		  			</div>

		  		</div>

		  	<% end %>
		  	<!-- Loans end -->


		  	<!-- Pagination -->
			<div class="center_pagination">
				<%= will_paginate @loans %>
			</div>



		</div>
		<!-- Table Panel End-->

</div>
<!-- End col-md-10 -->